### ISSUE TITLE
Foundation = Vakıf

### ISSUE THREAD

**Issue by TuanSSM** [gnu-tr/gnu-tr.github.io#1]
FSF (Özgür Yazılım Derneği) ❌
FSF (Özgür Yazılım Vakfı) ✅

**Comment by tansiret** [comment]
> FSF (Özgür Yazılım Derneği) x
> FSF (Özgür Yazılım Vakfı) white_check_mark

Bunu belirttiğin için teşekkürler. PR açmak ister misin yoksa biz mi düzeltelim?
